name: password mask
on: push
jobs:
  log:
    runs-on: ubuntu-latest
    env:
      PASSWORD: super
    steps:
      - run: echo "::add-mask::${PASSWORD}"
      - run: echo "${PASSWORD}"
      #アノテーション
      - run: echo "::error::This is an error"
      - run: echo "::warning::This is a warning"
      - run: echo "::notice::This is an notice"
    